Rails:
  Enabled: true

Rails/FindEach:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/RequestReferer:
  Enabled: true
  EnforcedStyle: referrer

Rails/ScopeArgs:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

GitHub/RailsApplicationRecord:
  Enabled: true


# Exclude Rails ERB files from incompatible cops

Lint/BlockAlignment:
  Exclude:
    - 'app/views/**/*.erb'

Style/For:
  Exclude:
    - 'app/views/**/*.erb'

Style/OneLineConditional:
  Exclude:
    - 'app/views/**/*.erb'

Style/Semicolon:
  Exclude:
    - 'app/views/**/*.erb'

Style/SpaceInsideParens:
  Exclude:
    - 'app/views/**/*.erb'

Style/StringLiterals:
  Exclude:
    - 'app/views/**/*.erb'

Style/TrailingBlankLines:
  Exclude:
    - 'app/views/**/*.erb'

Style/TrailingWhitespace:
  Exclude:
    - 'app/views/**/*.erb'
